---
title: "Using spatsoc for social network analysis"
author: "Alec Robitaille, Quinn Webber and Eric Vander Wal"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using spatsoc for social network analysis}
  %\VignetteEngine{knitr::knitr}
  %\VignetteEncoding{UTF-8}
---

```{r knitropts, include = FALSE}
knitr::opts_chunk$set(message = TRUE, 
                      warning = FALSE,
                      eval = FALSE, 
                      echo = FALSE)
```


#
since multi year 
we'll add splitby year

```{r}
library(spatsoc)
library(data.table)

# Read data as a data.table
DT <- fread(system.file("extdata", "DT.csv", package = "spatsoc"))

# Cast datetime column to POSIXct
DT[, datetime := as.POSIXct(datetime)]

# Year of row 
DT[, yr := year(datetime)]

# Temporal groups
group_times(DT, datetime = 'datetime', threshold = '5 minutes')

# Spatial groups
group_pts(
  DT,
  threshold = 50,
  id = 'ID',
  coords = c('X', 'Y'),
  timegroup = 'timegroup'
)
d <- dcast(DT, formula = group ~ ID, 
           fun.aggregate = length, value.var = 'group')

gbi <- as.matrix(d[, .SD, .SDcols = colnames(d)[!grepl('group', colnames(d))]])
rownames(gbi) <- d$group

library(asnipe)
net <- get_network(gbi, data_format = "GBI", association_index = "SRI")

randDT <-
  randomizations(
    DT,
    type = 'step',
    id = 'ID',
    datetime = 'timegroup',
    iterations = 500
  )

group_pts(
  randDT,
  threshold = 50,
  id = 'randomID',
  coords = c('X', 'Y'),
  timegroup = 'timegroup',
  splitBy = 'iteration'
)

```
