#' Calculate group polarization
#'
#' Polarization of group bearings from 0-1
#'
#' @param DT with bearing column generated by eg. bearing_sequential
#' @param bearing bearing column name, default 'bearing'
#' @param group group column name generated by eg. group_pts, default 'group'
#' @param degree boolean, if bearing is measured in degrees. See ?CircStats::r.test
#' @export
bearing_polarization <- function(DT,  bearing = 'bearing', group = 'group', degree = FALSE) {
  stopifnot(bearing %in% colnames(DT))
  stopifnot(group %in% colnames(DT))

  DT[, polarization := CircStats::r.test(.SD[[1]], degree = degree)$r.bar,
     by = c(group),
     .SDcols = c(bearing)]

  return(DT)
}
