#' Calculate absolute bearing to group leader
#'
#' Leader as identified using group_leader by first position along
#' group axis of movement (return_rank = TRUE)
#'
#' Note: coords must be in order x, y
#'
#' @param DT
#' @param coords character vector columns names for x and y
#' @param group group column name generated by eg. group_pts
bearing_to_leader <- function(DT, coords = c('x', 'y'), group = 'group') {
  stopifnot(first(coords) %in% colnames(DT))
  stopifnot(last(coords) %in% colnames(DT))
  stopifnot(group %in% colnames(DT))
  stopifnot('rank_dist_along_group_bearing' %in% colnames(DT))

  check_has_leader <- DT[, .(has_leader = any(rank_dist_along_group_bearing == 1)),
                         by = c(group)][!(has_leader)]

  if (check_has_leader[, .N > 0]) {
    warning('groups found missing leader (rank_dist_along_group_bearing == 1): \n',
            check_has_leader[, paste(group, collapse = ', ')])
  }

  DT[, temp_leader_xcol := .SD[which(rank_dist_along_group_bearing == 1)],
     .SDcols = first(coords), by = c(group)]
  DT[, temp_leader_ycol := .SD[which(rank_dist_along_group_bearing == 1)],
     .SDcols = last(coords), by = c(group)]

  DT[!group %in% check_has_leader$group, bearing_leader := fifelse(
    .SD[[first(coords)]] == .SD[['temp_leader_xcol']] &
      .SD[[last(coords)]] == .SD[['temp_leader_ycol']],
    NaN,
    atan2(.SD[['temp_leader_ycol']] - .SD[[last(coords)]],
          (.SD[['temp_leader_xcol']] - .SD[[first(coords)]]))
  )]
  DT[, c('temp_leader_xcol', 'temp_leader_ycol') := NULL]
  return(DT)
}
