#' Dyad centroid
#'
#' \code{centroid_dyad} calculates the centroid (mean location) of a dyad in
#' each observation identified by \code{edge_nn} or \code{edge_dist}. The
#' function accepts an edge list generated by \code{edge_nn} or \code{edge_dist}
#' and a \code{data.table} with relocation data appended with a \code{timegroup}
#' column from \code{group_times}. Relocation data should be in two columns
#' representing the X and Y coordinates.
#'
#' The \code{edges} and \code{DT} must be \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' The \code{edges} and \code{DT} are internally merged in this function using
#' the columns \code{id}, \code{dyadID} and \code{timegroup}. This function
#' expects a \code{dyadID} present, generated with the \code{dyad_id} function.
#' The \code{dyadID} and \code{timegroup} arguments expect the names of a column
#' in \code{edges} which correspond to the dyadID and timegroup columns. The
#' \code{id} and \code{timegroup} arguments expect the names of a column in
#' \code{DT} which correspond to the X and Y coordinates and group columns. The
#' \code{na.rm} argument is passed to the \code{rowMeans} function to control if
#' NA values are removed before calculation.
#'
#' @param edges edge list generated generated by \code{edge_dist} or
#'  \code{edge_nn}, with dyad ID column generated by \code{dyad_ID}
#' @param DT input data.table with timegroup column generated with
#'   \code{group_times} matching the input data.table used to generate the edge
#'   list with \code{edge_nn} or \code{edge_dist}
#' @inheritParams group_pts
#' @param na.rm if NAs should be removed in calculating mean location, see
#'   \code{rowMeans}
