#' Fusion centroid
#'
#' `centroid_fusion` calculates the centroid (mean location) of each
#' timestep in fusion events. The function expects an edge-list of fusion events
#' identified by `fusion_id` from edge-lists generated with
#' `edge_dist` and a `data.table` with relocation data appended with a
#' `timegroup` column from `group_times`. It is recommended to use the
#' argument `fillNA = FALSE` for `edge_dist` when using
#' `centroid_fusion` to avoid unnecessarily merging additional rows.
#' Relocation data should be in two columns representing the X and Y
#' coordinates.
#'
#' The `edges` and `DT` must be `data.table`. If your data is a
#' `data.frame`, you can convert it by reference using
#' [data.table::setDT()] or by reassigning using
#' [data.table::data.table()].
#'
#' The `edges` and `DT` are internally merged in this function using
#' the columns `timegroup` (from `group_times`) and `ID1` and
#' `ID2` (in `edges`, from `dyad_id`) and `id` (in
#' `DT`). This function expects a `fusionID` present, generated with
#' the `fusion_id` function. The `timegroup` argument expects the
#' names of a column in `edges` which correspond to the timegroup column.
#' The `id`, `coords` and `timegroup` arguments expect the names
#' of a column in `DT` which correspond to the id, X and Y coordinates and
#' timegroup columns. The `na.rm` argument is passed to the `rowMeans`
#' function to control if NA values are removed before calculation.
#'
#' @param edges edge-list generated generated by `edge_dist` or
#'  `edge_nn`, with fusionID column generated by `fusion_id`
#' @param DT input data.table with timegroup column generated with
#'   `group_times` matching the input data.table used to generate the edge
#'   list with `edge_nn` or `edge_dist`
#' @inheritParams group_pts
#' @param na.rm if NAs should be removed in calculating mean location, see
#'   `rowMeans`
#'
#' @return `centroid_fusion` returns the input `edges` appended with
#'   centroid columns for the X and Y coordinate columns.
#'
#'   These columns represents the centroid coordinate columns for each timestep
#'   in a fusion event. The naming of these columns will correspond to the
#'   provided coordinate column names prefixed with "centroid_".
#'
#'   Note: due to the merge required within this function, the output needs to
#'   be reassigned unlike some other `spatsoc` functions like
#'   `fusion_id` and `group_pts`. See details in
#'  [FAQ](https://docs.ropensci.org/spatsoc/articles/faq.html).
#'
#'   A message is returned when centroid columns are already exists in the input
#'   `edges`, because they will be overwritten.
#'
#' @export
#' @family Centroid functions
#' @seealso [fusion_id] [edge_dist] [group_pts]
#' @examples
#' # Load data.table
#' library(data.table)
#' \dontshow{data.table::setDTthreads(1)}
#'
#' # Read example data
#' DT <- fread(system.file("extdata", "DT.csv", package = "spatsoc"))
#'
#' # Cast the character column to POSIXct
#' DT[, datetime := as.POSIXct(datetime, tz = 'UTC')]
#'
#' # Temporal grouping
#' group_times(DT, datetime = 'datetime', threshold = '20 minutes')
#'
#' # Edge-list generation
#' edges <- edge_dist(
#'     DT,
#'     threshold = 100,
#'     id = 'ID',
#'     coords = c('X', 'Y'),
#'     timegroup = 'timegroup',
#'     returnDist = TRUE,
#'     fillNA = FALSE
#'   )
#'
#' # Generate dyad id
#' dyad_id(edges, id1 = 'ID1', id2 = 'ID2')
#'
#' # Generate fusion id
#' fusion_id(edges, threshold = 100)
#'
#' # Calculate fusion centroid
#' centroids <- centroid_fusion(
#'   edges,
#'   DT,
#'   id = 'ID',
#'   coords = c('X', 'Y'),
#'   timegroup = 'timegroup', na.rm = TRUE
#' )
#'
#' print(centroids)
centroid_fusion <- function(
    edges = NULL,
    DT = NULL,
    id = NULL,
    coords = NULL,
    timegroup = 'timegroup',
    na.rm = FALSE) {
  # Due to NSE notes in R CMD check
  fusionID <- NULL

  if (is.null(DT)) {
    stop('input DT required')
  }

  if (is.null(edges)) {
    stop('input edges required')
  }

  if (is.null(id)) {
    stop('id column name required')
  }

  if (length(coords) != 2) {
    stop('coords requires a vector of column names for coordinates X and Y')
  }

  if (is.null(timegroup)) {
    stop('timegroup column name required')
  }

  check_cols_edges <- c('fusionID', 'ID1', 'ID2', timegroup)
  if (!all((check_cols_edges %in% colnames(edges)))) {
    stop(paste0(
      as.character(paste(setdiff(
        check_cols_edges,
        colnames(edges)
      ), collapse = ', ')),
      ' field(s) provided are not present in input edges'
    ))
  }

  if (!all((
    c(id, coords, timegroup) %in% colnames(DT)
  ))) {
    stop(paste0(
      as.character(paste(setdiff(
        c(id, coords, timegroup),
        colnames(DT)
      ), collapse = ', ')),
      ' field(s) provided are not present in input DT'
    ))
  }

  if (!all((DT[, vapply(.SD, is.numeric, TRUE), .SDcols = coords]))) {
    stop('coords must be numeric')
  }

  if (is.null(na.rm)) {
    stop('na.rm is required')
  }

  if (!is.logical(na.rm)) {
    stop('na.rm should be a boolean (TRUE/FALSE), see ?mean')
  }

  xcol <- data.table::first(coords)
  ycol <- data.table::last(coords)

  out_xcol <- paste0('centroid_', gsub(' ', '', xcol))
  out_ycol <- paste0('centroid_', gsub(' ', '', ycol))

  id1_coords <- paste0('id1_', coords)
  id2_coords <- paste0('id2_', coords)

  m <- merge(edges,
             DT[, .SD, .SDcols = c(coords, id, 'timegroup')],
             by.x = c('ID1', timegroup),
             by.y = c(id, timegroup),
             all.x = TRUE,
             sort = FALSE)
  data.table::setnames(m, coords, id1_coords)
  m <- merge(m,
             DT[, .SD, .SDcols = c(coords, id, 'timegroup')],
             by.x = c('ID2', timegroup),
             by.y = c(id, timegroup),
             all.x = TRUE,
             sort = FALSE)
  data.table::setnames(m, coords, id2_coords)

  if (out_xcol %in% colnames(m)) {
    message(paste(out_xcol, 'column will be overwritten by this function'))
    data.table::set(m, j = out_xcol, value = NULL)
  }

  if (out_ycol %in% colnames(m)) {
    message(paste(out_ycol, 'column will be overwritten by this function'))
    data.table::set(m, j = out_ycol, value = NULL)
  }

  m[, c(out_xcol) := rowMeans(.SD, na.rm = na.rm),
    .SDcols = c(data.table::first(id1_coords), data.table::first(id2_coords))]
  m[, c(out_ycol) := rowMeans(.SD, na.rm = na.rm),
    .SDcols = c(data.table::last(id1_coords), data.table::last(id2_coords))]

  data.table::set(m, j = c(id1_coords, id2_coords), value = NULL)
  data.table::setcolorder(m, colnames(edges))

  m[is.na(fusionID), (c(out_xcol, out_ycol)) := NA]

  return(m[])
}
