#' Distance to group centroid
#'
#' \code{distance_to_centroid} calculates the distance of each relocation to the
#' centroid of the spatiotemporal group identified by \code{group_pts}. The
#' function accepts a \code{data.table} with relocation data appended with a
#' \code{group} column from \code{group_pts} and centroid columns from
#' \code{centroid_group}. Relocation data should be in two columns representing
#' the X and Y coordinates.
#'
#' The \code{DT} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' This function expects a \code{group} column present generated with the
#' \code{group_pts} function and centroid coordinate columns generated with the
#' \code{centroid_group} function. The \code{coords} and \code{group} arguments
#' expect the names of columns in \code{DT} which correspond to the X and Y
#' coordinates and group columns. The \code{return_rank} argument controls if
#' the rank of each individual's distance to the group centroid is also
#' returned. The \code{ties.method} argument is passed to
#' \code{data.table::frank}, see details at
#' \code{\link[data.table:frank]{?data.table::frank}}.
#'
#' @inheritParams group_pts
#' @param group group column name, generated by \code{group_pts}, default
#'   'group'
#' @param return_rank boolean if rank distance should also be returned, default
#'   FALSE
#' @param ties.method see \code{\link[data.table:frank]{?data.table::frank}}
#'
#' @return \code{distance_to_centroid} returns the input \code{DT} appended with
#'   a \code{distance_centroid} column indicating the distance to group centroid
#'   and, optionally, a \code{rank_distance_centroid} column indicating the
#'   within group rank distance to group centroid (if \code{return_rank =
#'   TRUE}).
#'
#'   A message is returned when \code{distance_centroid} and optional
#'   \code{rank_distance_centroid} columns already exist in the input \code{DT},
#'   because they will be overwritten.
#'
#' @export
#' @family Distance functions
#' @seealso [centroid_group], [group_pts]
#' @references
#' See examples of using distance to group centroid:
#'  * <https://doi.org/10.1016/j.anbehav.2021.08.004>
#'  * <https://doi.org/10.1111/eth.12336>
#'  * <https://doi.org/10.1007/s13364-018-0400-2>

  stopifnot(length(coords) == 2)

  xcol <- first(coords)
  ycol <- last(coords)
  group_xcol <- paste0(pre, xcol)
  group_ycol <- paste0(pre, ycol)

  stopifnot(xcol %in% colnames(DT))
  stopifnot(ycol %in% colnames(DT))
  stopifnot(group_xcol %in% colnames(DT))
  stopifnot(group_ycol %in% colnames(DT))
  stopifnot(group %in% colnames(DT))


  DT[, dist_group_centroid :=
       sqrt((.SD[[xcol]] - .SD[[group_xcol]])^2 +
              (.SD[[ycol]] - .SD[[group_ycol]])^2)]

  if (return_rank) {
    DT[, N_by_group := .N, by = c(group)]
    DT[, rank_dist_group_centroid :=
         data.table::frank(dist_group_centroid),
       by = c(group)]
  }
  return(DT[])
}
