#' Distance to group leader
#'
#' `distance_to_leader` calculates the distance to the leader of each
#' spatiotemporal group. The function expects a `data.table` with
#' relocation data appended with a `rank_position_group_direction` column
#' indicating the ranked position along the group direction generated with
#' `leader_direction_group(return_rank = TRUE)`. Relocation data should be
#' in planar coordinates provided in two columns representing the X and Y
#' coordinates.
#'
#' The `DT` must be a `data.table`. If your data is a
#' `data.frame`, you can convert it by reference using
#' [data.table::setDT()] or by reassigning using
#' [data.table::data.table()].
#'
#' This function expects a `rank_position_group_direction` column
#' generated with `leader_direction_group(return_rank = TRUE)`,
#' a `group` column generated with the
#' `group_pts` function. The `coords` and `group` arguments
#' expect the names of columns in `DT` which correspond to the X and Y
#' coordinates and group columns.
#'
#' The `crs` argument expects a character string or numeric defining the
#' coordinate reference system to be passed to [sf::st_crs]. For example, for
#' UTM zone 36S (EPSG 32736), the crs argument is `crs = "EPSG:32736"` or
#' `crs = 32736`. See <https://spatialreference.org> for a list of EPSG codes.
#'
#' @param DT input data.table with 'rank_position_group_direction' column
#'   generated by `leader_direction_group` and group column generated by
#'   `group_pts`
#' @inheritParams leader_direction_group
#'
#' @return `distance_to_leader` returns the input `DT` appended with
#'   a `distance_leader` column indicating the distance to the group
#'   leader.
#'
#'   A message is returned when the `distance_leader` column already
#'   exist in the input `DT` because it will be overwritten.
#'
#'   See details for appending outputs using modify-by-reference in the
#'   [FAQ](https://docs.ropensci.org/spatsoc/articles/faq.html).
#'
#' @export
#' @family Distance functions
#' @seealso [direction_to_leader], [leader_direction_group], [group_pts]
#' @references
#'
#' See examples of using distance to leader and position within group:
#'  * \doi{doi:10.1111/jfb.15315}
#'  * \doi{doi:10.1098/rspb.2017.2629}
#'  * \doi{doi:10.1016/j.anbehav.2023.09.009}
#'
#' @examples
#' # Load data.table
#' library(data.table)
#' \dontshow{data.table::setDTthreads(1)}
#'
#' # Read example data
#' DT <- fread(system.file("extdata", "DT.csv", package = "spatsoc"))
#'
#' # Cast the character column to POSIXct
#' DT[, datetime := as.POSIXct(datetime, tz = 'UTC')]
#'
#' # (Subset example data to reduce example run time)
#' DT <- DT[year(datetime) == 2016]
#'
#' # Temporal grouping
#' group_times(DT, datetime = 'datetime', threshold = '20 minutes')
#'
#' # Spatial grouping with timegroup
#' group_pts(DT, threshold = 50, id = 'ID',
#'           coords = c('X', 'Y'), timegroup = 'timegroup')
#'
#' # Calculate direction at each step
#' direction_step(
#'   DT = DT,
#'   id = 'ID',
#'   coords = c('X', 'Y'),
#'   crs = 32736
#' )
#'
#' # Calculate group centroid
#' centroid_group(DT, coords = c('X', 'Y'))
#'
#' # Calculate group direction
#' direction_group(DT)
#'
#' # Calculate leader in terms of position along group direction
#' leader_direction_group(
#'   DT,
#'   coords = c('X', 'Y'),
#'   return_rank = TRUE
#' )
#'
#' # Calculate distance to leader
#' distance_to_leader(DT, coords = c('X', 'Y'))
distance_to_leader <- function(
    DT = NULL,
    coords = NULL,
    group = 'group') {
  # Due to NSE notes
  distance_leader <- zzz_N_by_group <- rank_position_group_direction <-
    has_leader <- . <- NULL

  assert_not_null(DT)
  assert_is_data_table(DT)
  assert_not_null(group)
  assert_are_colnames(DT, group)

  assert_are_colnames(DT, coords)
  assert_length(coords, 2)
  assert_col_inherits(DT, coords, 'numeric')

  leader_col <- 'rank_position_group_direction'
  assert_are_colnames(DT, leader_col,
                      ', did you run leader_direction_group(return_rank = TRUE)?')
  assert_col_inherits(DT, leader_col, 'numeric')

  out_col <- 'distance_leader'
  if (out_col %in% colnames(DT)) {
    message(
      paste0(out_col, ' column will be overwritten by this function')
    )
    data.table::set(DT, j = out_col, value = NULL)
  }

  DT[, zzz_N_by_group := .N, by = c(group)]

  check_leaderless <- DT[, .(
    has_leader = any(rank_position_group_direction == 1)),
    by = c(group)][!(has_leader)]

  if (check_leaderless[, .N > 0]) {
    warning(
      'groups found missing leader (rank_position_group_direction == 1): \n',
      check_leaderless[, paste(group, collapse = ', ')]
    )
  }

  DT[!group %in% check_leaderless$group,
     c(out_col) := fifelse(
       zzz_N_by_group > 1,
       as.matrix(
         stats::dist(cbind(.SD[[1]], .SD[[2]]))
       )[, which(.SD[[3]] == 1)],
       0
     ),
     .SDcols = c(coords, 'rank_position_group_direction'),
     by = c(group)]

  data.table::set(DT, j = 'zzz_N_by_group', value = NULL)

  return(DT[])
}
