#' Directional alignment based edge-lists
#'
#' \code{edge_alignment} returns edge-lists defined by directional alignment
#' (difference in movement direction) between individuals. The function expects
#' a \code{data.table} with relocation data and individual identifiers, a
#' direction column (generated by \code{direction_step}) and timegroup column
#' (generated by \code{group_times}).
#'
#' The \code{DT} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}}.
#'
#' The \code{id}, \code{direction}, \code{timegroup}, and optional \code{group}
#' and \code{splitBy} arguments expect the names of a column in \code{DT} which
#' correspond to the individual identifier, direction (generated by
#' \code{direction_step}), timegroup (generated by \code{group_times}), group
#' (generated by \code{group_pts}) and additional grouping columns.
#'
#' There are two approaches to spatially restricting the calculation of
#' directional alignment. The \code{group} argument can be used to pass the
#' output group column from \code{group_pts} to calculate direction alignment
#' within spatiotemporal groups. Alternatively, the output of
#' \code{edge_alignment} can be merged with the output of \code{edge_dist} to
#' compare the difference in direction to the distance between individuals.
#'
#' The \code{splitBy} argument offers further control over the calculation of
#' directional alignment.  If within your \code{DT}, you have multiple
#' populations, subgroups or other distinct parts, you can provide the name of
#' the column which identifies them to \code{splitBy}. \code{edge_alignment}
#' will only consider rows within each \code{splitBy} subgroup.
#'
#' @inheritParams edge_dist
#' @inheritParams direction_polarization
#' @inheritParams diff_rad
#' @param timegroup character string of timegroup column name, default "timegroup"
#' @param group (optional) character string of group column name, used to restrict
#' the calculation of directional alignment to within spatiotemporal groups
#' @param splitBy (optional) vector of column names indicating subgroups within
#'   which the direction alignment will be calculated
