#' Behavioural zones
#'
#' \code{edge_zones} returns edge-lists defined by behavioural zones (Couzin
#' 2002). The function expects a distance based edge-list generated by
#' \code{edge_dist} (optionally with directions measured by
#' \code{direction_step} and \code{edge_direction}), zone thresholds, labels
#' and (optionally) a blind volume.
#'
#' \code{edge_zones} uses interindividual distances, and optionally directions,
#' to assign neighboring individuals to a focal individual's behavioural zones.
#' The user provides zone thresholds (eg. 25 m, 100 m, 250 m) along with zone
#' labels (eg. zone of repulsion, zone of orientation, zone of attraction),
#' according to their objectives, study species and system. The optional blind
#' volume can be provided to define a range of interindividual directions that
#' correspond to the limits of the focal individual's perception.
#'
#' Two workflows for this function exist, depending on if the blind volume
#' argument is used:
#'
#' a) If the blind volume is not provided, simply provide your distance based
#' edge-lists from \code{edge_dist} with zone thresholds and labels.
#' b) If the blind volume is provided, the following order of functions is
#' expected to ensure the relevant direction columns are available:
#'    1. direction_step(DT)
#'    1. edges <- edge_dist(DT)
#'    1. dyad_directions <- edge_direction(edges, DT)
#'    1. edge_zones(dyad_directions)
#'
#'  Interindividual distances are converted into behavioural zones using
#'  \code{cut}. The thresholds provided are used as cut points for a series of
#'  intervals that are open on the left and closed on the right, starting at 0.
#'  See details in \code{\link[base:cut]{base::cut}}.
#'
#'  The (optional) blind volume defines the range of interindividual directions
#'  between the focal individual (ID1) and the neighbour (ID2) that is outside
#'  of the focal individual's perception. The interindividual direction (column
#'  "direction_dyad" from \code{edge_direction}) is made relative to the focal
#'  individual's movement direction (column "direction" from
#'  \code{direction_step}). The argument blind_volume expects a single value to
#'  define a symmetrical window behind the focal individual's movement direction
#'  eg. where blind_volume = 2, the symmetrical window is from (-2, 2).
#'
#' The \code{edges} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#' @export
#' TODO: @references (Couzin 2002, used in eg. Lukeman 2010, Klamser 2021, Klamser 2021)
#' TODO: @inheritParams centroid_dyad
edge_zones <- function(
    edges = NULL,
    zone_thresholds = NULL,
    zone_labels = NULL,
    blind_volume = NULL) {

  # TODO: check if
  #  - direction
  #  - direction_dyad
  #  - zones
  #    - zone repulsion < orientation < attraction
  #  - blind_volume

  edges[, zones := cut(distance, breaks = c(0, zone_thresholds),
                       labels = c(zone_labels))]

  if (!is.null(blind_volume)) {
    edges[, direction_dyad_relative :=
            diff_rad(direction, direction_dyad, signed = TRUE)]

    edges[abs(direction_dyad_relative) > blind_volume & !is.na(zones),
          zones := 'blind']
  }

}
