#' Direction based edge-lists
#'
#' \code{edge_direction} returns edge lists defined by the direction between
#' individuals. The function expects a distance based edge-list generated by
#' \code{edge_nn} or \code{edge_dist} and a \code{data.table} with relocation
#' data appended with a \code{timegroup} column from \code{group_times}.
#' It is required to use the argument \code{fillNA = FALSE} for
#' \code{edge_dist} to ensure there are no NAs in the coordinate columns.
#' Relocation data should be in two columns representing the X and Y coordinates.
#'
#' The \code{edges} and \code{DT} must be \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' The \code{projection} argument expects a character string or numeric defining
#' the coordinate reference system to be passed to [sf::st_crs]. For example,
#' for UTM zone 36S (EPSG 32736), the projection argument is
#' \code{projection = "EPSG:32736"} or \code{projection = 32736}. See
#' <https://spatialreference.org> for a list of EPSG codes.
#'
#' The \code{edges} and \code{DT} are internally merged in this function using
#' the columns \code{id}, \code{dyadID} and \code{timegroup}. This function
#' expects a \code{dyadID} present, generated with the \code{dyad_id} function.
#' The \code{id}, \code{coords} and \code{timegroup} arguments expect the names
#' of columns which correspond to the ID, X and Y coordinates and timegroup
#' columns.
#'
#' @inheritParams centroid_dyad
#' @inheritParams direction_step
#' @inheritParams edge_alignment
#'
#' @references
#'
#' See examples of measuring the direction between individuals:
#'  * \doi{doi:10.1098/rsif.2013.0529}
#'  * \doi{doi:10.1098/rstb.2019.0380}
#'  * \doi{doi:10.1111/jfb.15315}
#'
#' @return \code{edge_direction} returns the input \code{edges} appended with
#'  a "direction_dyad" column representing the direction between ID1 and ID2.
#'
#'  TODO: if direction is in DT, preserved for ID1
#'
#'  The direction between individuals is calculated with
#'  \code{\link[lwgeom:st_geod_azimuth]{lwgeom::st_geod_azimuth}}.
#'
#'  Note: due to the merge required within this function, the output needs to be
#'  reassigned unlike some other \code{spatsoc} functions like \code{dyad_id}
#'  and \code{group_pts}. See details in
#'  [FAQ](https://docs.ropensci.org/spatsoc/articles/faq.html).
#'
#' @export
#' @family Edge-list generation
#' @family Direction functions
#' @seealso [dyad_id] [edge_dist] [edge_nn] [group_times]
#' @examples
#' # Load data.table
#' library(data.table)
#' \dontshow{data.table::setDTthreads(1)}
#'
#' # Read example data
#' DT <- fread(system.file("extdata", "DT.csv", package = "spatsoc"))
#'
#' # Cast the character column to POSIXct
#' DT[, datetime := as.POSIXct(datetime, tz = 'UTC')]
#'
#' # Temporal grouping
#' group_times(DT, datetime = 'datetime', threshold = '20 minutes')
#'
#' # Edge list generation
#' edges <- edge_dist(
#'     DT,
#'     threshold = 100,
#'     id = 'ID',
#'     coords = c('X', 'Y'),
#'     timegroup = 'timegroup',
#'     returnDist = TRUE,
#'     fillNA = FALSE
#'   )
#'
#' # Generate dyad id
#' dyad_id(edges, id1 = 'ID1', id2 = 'ID2')
#'
#' # Direction based edge-lists
#' dyad_directions <- edge_direction(
#'   edges,
#'   DT,
#'   id = 'ID',
#'   coords = c('X', 'Y'),
#'   projection = 32736,
#'   timegroup = 'timegroup'
#' )
#'
#' print(dyad_directions)
edge_direction <- function(
    edges = NULL,
    DT = NULL,
    id = NULL,
    coords = NULL,
    projection = NULL,
    timegroup = 'timegroup') {

  if (is.null(DT)) {
    stop('input DT required')
  }

  if (is.null(edges)) {
    stop('input edges required')
  }

  if (is.null(id)) {
    stop('id column name required')
  }

  if (length(coords) != 2) {
    stop('coords requires a vector of column names for coordinates X and Y')
  }

  if (is.null(timegroup)) {
    stop('timegroup required')
  }

  if (!'timegroup' %in% colnames(edges)) {
    stop('timegroup field provided are not present in input edges')
  }

  if (!'dyadID' %in% colnames(edges)) {
    stop('dyadID not present in input edges, did you run dyad_id?')
  }

  if (any(!(
    c(id, coords, timegroup) %in% colnames(DT)
  ))) {
    stop(paste0(
      as.character(paste(setdiff(
        c(id, coords, timegroup),
        colnames(DT)
      ), collapse = ', ')),
      ' field(s) provided are not present in input DT'
    ))
  }

  if (any(!(DT[, vapply(.SD, is.numeric, TRUE), .SDcols = coords]))) {
    stop('coords must be numeric')
  }

  if (is.null(projection)) {
    stop('projection required')
  }

  xcol <- data.table::first(coords)
  ycol <- data.table::last(coords)

  out_col <- 'direction_dyad'

  id1_coords <- paste0('id1_', coords)
  id2_coords <- paste0('id2_', coords)

  merge_cols <- c(coords, id, timegroup)
  m <- merge(edges,
             DT[, .SD,
                .SDcols = if ('direction' %in% colnames(DT)) {
                  c(merge_cols, 'direction')
                }],
             by.x = c('ID1', timegroup),
             by.y = c(id, timegroup),
             all.x = TRUE,
             sort = FALSE)
  data.table::setnames(m, coords, id1_coords)
  m <- merge(m,
             DT[, .SD, .SDcols = merge_cols],
             by.x = c('ID2', timegroup),
             by.y = c(id, timegroup),
             all.x = TRUE,
             sort = FALSE)
  data.table::setnames(m, coords, id2_coords)

  if (out_col %in% colnames(m)) {
    message(paste(out_col, 'column will be overwritten by this function'))
    data.table::set(m, j = out_col, value = NULL)
  }

  if (sf::st_is_longlat(projection)) {
    m[, (out_col) :=
        lwgeom::st_geod_azimuth(
          sf::st_as_sf(.SD, coords = id1_coords, crs = projection),
          sf::st_as_sf(.SD, coords = id2_coords, crs = projection)
        )]
  } else if (!sf::st_is_longlat(projection)) {
    m[, (out_col) :=
        lwgeom::st_geod_azimuth(
          sf::st_transform(
            sf::st_as_sf(.SD, coords = id1_coords, crs = projection),
            crs = 4326),
          sf::st_transform(
            sf::st_as_sf(.SD, coords = id2_coords, crs = projection),
            crs = 4326)
        )]
  }

  data.table::set(m, j = c(id1_coords, id2_coords), value = NULL)
  data.table::setcolorder(m, c(timegroup, 'ID1', 'ID2', 'dyadID'))

  return(m[])
}
