#' Directional alignment based edge-lists
#'
#' \code{edge_alignment} returns edge-lists defined by directional alignment
#' (difference in movement direction) between individuals. The function expects
#' a \code{data.table} with relocation data and individual identifiers, a
#' direction column (generated by \code{direction_step}) and timegroup column
#' (generated by \code{group_times}).
#'
#' The \code{DT} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}}.
#'
#' The \code{id}, \code{direction}, \code{timegroup}, and optional \code{group}
#' and \code{splitBy} arguments expect the names of a column in \code{DT} which
#' correspond to the individual identifier, direction (generated by
#' \code{direction_step}), timegroup (generated by \code{group_times}), group
#' (generated by \code{group_pts}) and additional grouping columns.
#'
#' There are two approaches to spatially restricting the calculation of
#' directional alignment. The \code{group} argument can be used to pass the
#' output group column from \code{group_pts} to calculate direction alignment
#' within spatiotemporal groups. Alternatively, the output of
#' \code{edge_alignment} can be merged with the output of \code{edge_dist} to
#' compare the difference in direction to the distance between individuals.
#'
#' The \code{splitBy} argument offers further control over the calculation of
#' directional alignment.  If within your \code{DT}, you have multiple
#' populations, subgroups or other distinct parts, you can provide the name of
#' the column which identifies them to \code{splitBy}. \code{edge_alignment}
#' will only consider rows within each \code{splitBy} subgroup.
#'
#' @inheritParams edge_dist
#' @inheritParams direction_polarization
#' @inheritParams diff_rad
#' @param timegroup character string of timegroup column name, default "timegroup"
#' @param group (optional) character string of group column name, used to restrict
#' the calculation of directional alignment to within spatiotemporal groups
#' @param splitBy (optional) vector of column names indicating subgroups within
#'   which the direction alignment will be calculated
#'
#' @return \code{edge_alignment} returns a \code{data.table} with columns ID1, ID2,
#'   timegroup, and a 'direction_diff' column indicating the difference in direction
#'   between ID1 and ID2, along with any columns provided in splitBy.
#'
#'  Note: unlike many other functions (eg. \code{group_pts}) in \code{spatsoc},
#'  \code{edge_alignment} needs to be reassigned. See details in
#'  [FAQ](https://docs.ropensci.org/spatsoc/articles/faq.html).
#'
#' @export
#'
#' @family Edge-list generation
#' @family Direction functions
#'
#' @examples
#' # Load data.table
#' library(data.table)
#' \dontshow{
#' data.table::setDTthreads(1)
#' }
#'
#' # Read example data
#' DT <- fread(system.file('extdata', 'DT.csv', package = 'spatsoc'))
#'
#' # Cast the character column to POSIXct
#' DT[, datetime := as.POSIXct(datetime, tz = 'UTC')]
#'
#' # Temporal grouping
#' group_times(DT, datetime = 'datetime', threshold = '20 minutes')
#'
#' # Calculate direction
#' direction_step(
#'   DT = DT,
#'   id = 'ID',
#'   coords = c('X', 'Y'),
#'   projection = 32736
#' )
#'
#' # Calculate directional alignment edge-list
#' align <- edge_alignment(
#'   DT,
#'   id = 'ID',
#'   timegroup = 'timegroup',
#'   signed = FALSE
#' )
#'
#' # Or, calculate directional alignment within spatiotemporal groups
#' group_pts(DT, threshold = 5, id = 'ID',
#'           coords = c('X', 'Y'), timegroup = 'timegroup')
#'
#' align_group <- edge_alignment(
#'   DT,
#'   id = 'ID',
#'   timegroup = 'timegroup',
#'   group = 'group',
#'   signed = FALSE
#' )
