#' Direction based edge-lists
#'
#' \code{edge_direction} returns edge lists defined by the direction between
#' individuals. The function expects a distance based edge-list generated by
#' \code{edge_nn} or \code{edge_dist} and a \code{data.table} with relocation
#' data appended with a \code{timegroup} column from \code{group_times}.
#' It is required to use the argument \code{fillNA = FALSE} for
#' \code{edge_dist} to ensure there are no NAs in the coordinate columns.
#' Relocation data should be in two columns representing the X and Y coordinates.
#'
#' The \code{edges} and \code{DT} must be \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' The \code{projection} argument expects a character string or numeric defining
#' the coordinate reference system to be passed to [sf::st_crs]. For example,
#' for UTM zone 36S (EPSG 32736), the projection argument is
#' \code{projection = "EPSG:32736"} or \code{projection = 32736}. See
#' <https://spatialreference.org> for #' a list of EPSG codes.
#'
#' The \code{edges} and \code{DT} are internally merged in this function using
#' the columns \code{id}, \code{dyadID} and \code{timegroup}. This function
#' expects a \code{dyadID} present, generated with the \code{dyad_id} function.
#' The \code{dyadID} and \code{timegroup} arguments expect the names of a column
#' in \code{edges} which correspond to the dyadID and timegroup columns. The
#' \code{id} and \code{timegroup} arguments expect the names of a column in
#' \code{DT} which correspond to the X and Y coordinates and group columns.
#' @family Edge-list generation
edge_direction <- function(
    edges = NULL,
    DT = NULL,
    id = NULL,
    coords = NULL,
    projection = NULL,
    timegroup = 'timegroup') {

  if (is.null(DT)) {
    stop('input DT required')
  }

  if (is.null(edges)) {
    stop('input edges required')
  }

  if (is.null(id)) {
    stop('id column name required')
  }

  if (length(coords) != 2) {
    stop('coords requires a vector of column names for coordinates X and Y')
  }

  if (is.null(timegroup)) {
    stop('timegroup required')
  }

  if (any(!(
    c('dyadID', timegroup) %in% colnames(edges)
  ))) {
    stop(paste0(
      as.character(paste(setdiff(
        c('dyadID', timegroup),
        colnames(edges)
      ), collapse = ', ')),
      ' field(s) provided are not present in input DT'
    ))
  }

  if (any(!(
    c(id, coords, timegroup) %in% colnames(DT)
  ))) {
    stop(paste0(
      as.character(paste(setdiff(
        c(id, coords, timegroup),
        colnames(DT)
      ), collapse = ', ')),
      ' field(s) provided are not present in input DT'
    ))
  }

  if (any(!(DT[, vapply(.SD, is.numeric, TRUE), .SDcols = coords]))) {
    stop('coords must be numeric')
  }

  xcol <- data.table::first(coords)
  ycol <- data.table::last(coords)

  out_col <- 'direction_dyad'

  id1_coords <- paste0('id1_', coords)
  id2_coords <- paste0('id2_', coords)

  m <- merge(edges,
             DT[, .SD, .SDcols = c(coords, id, 'timegroup')],
             by.x = c('ID1', timegroup),
             by.y = c(id, timegroup),
             all.x = TRUE,
             sort = FALSE)
  data.table::setnames(m, coords, id1_coords)
  m <- merge(m,
             DT[, .SD, .SDcols = c(coords, id, 'timegroup')],
             by.x = c('ID2', timegroup),
             by.y = c(id, timegroup),
             all.x = TRUE,
             sort = FALSE)
  data.table::setnames(m, coords, id2_coords)

  if (out_col %in% colnames(m)) {
    message(paste(out_col, 'column will be overwritten by this function'))
    data.table::set(m, j = out_col, value = NULL)
  }


  m[, out_col :=
      lwgeom::st_geod_azimuth(
        sf::st_as_sf(.SD, coords = id1_coords, crs = projection),
        sf::st_as_sf(.SD, coords = id2_coords, crs = projection)
      )]

  data.table::set(m, j = c(id1_coords, id2_coords), value = NULL)
  data.table::setcolorder(m, colnames(edges))

  return(m[])
}
