#' Group mean bearing
#'
#' @param DT
#' @param bearing bearing column name generated by eg. bearing_sequential,
#' default 'bearing'
#' @param group group column generated by eg. group_pts
#' @export
group_bearing <- function(DT, bearing = 'bearing', group = 'group') {
  stopifnot(is.data.table(DT))
  stopifnot(bearing %in% colnames(DT))
  stopifnot(group %in% colnames(DT))

  DT[, group_mean_bearing := CircStats::circ.mean(.SD[[1]]),
     by = c(group),
     .SDcols = c(bearing)]

  return(DT)
}
