#' Leadership in directional correlation delay
#'
#' Given the directional correlation delay, \code{leader_edge_delay}
#' calculates the mean directional correlation delay for individuals in a
#' group to identify leadership patterns.
#'
#' The function accepts an edge list from \code{edge_delay} with columns
#' "dir_corr_delay" indicating the directional correlation delay between
#' individuals and "diff_direction" indicating the unsigned difference in
#' movement directions at the temporal delay.
#'
#' The \code{edge} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' If \code{return_rank} is TRUE, the \code{group} argument is required to
#' specify the group column generated by \code{group_pts}. The
#' \code{ties.method} argument is passed to \code{data.table::frank}, see
#' details at \code{\link[data.table:frank]{?data.table::frank}}.
#'
#' @return \code{leader_edge_delay} returns the input \code{edges} appended with
#'   a \code{mean_delay} column indicating the mean directional correlation
#'   delay and, optionally when \code{return_rank = TRUE}, a
#'   \code{rank_mean_delay} column indicating the ranked mean directional
#'   correlation delay.
#'
#' @inheritParams edge_delay
#'
#' @export
#' @seealso \code{\link{edge_delay}}
#' @family Leadership functions
#'
#' @references
#' See examples of measuring leadership using the directional correlation
#' delay:
#'  * <https://doi.org/10.1016/j.anbehav.2013.07.005>
#'  * <https://doi.org/10.1073/pnas.1305552110>
#'  * <https://doi.org/10.1111/jfb.15315>
#'  * <https://doi.org/10.1371/journal.pcbi.1003446>
#'
#' @examples
#' # Load data.table
#' library(data.table)
#' \dontshow{data.table::setDTthreads(1)}
#' # Read example data
#' DT <- fread(system.file("extdata", "DT.csv", package = "spatsoc"))
#'
#' # Select only individuals A, B, C for this example
#' DT <- DT[ID %in% c('A', 'B', 'C')]
#'
#' # Cast the character column to POSIXct
#' DT[, datetime := as.POSIXct(datetime, tz = 'UTC')]
#'
#' # Temporal grouping
#' group_times(DT, datetime = 'datetime', threshold = '20 minutes')
#'
#' # Calculate direction
#' direction_step(
#'   DT = DT,
#'   id = 'ID',
#'   coords = c('X', 'Y'),
#'   projection = 32736
#' )
#'
#' # Distance based edge list generation
#' edges <- edge_dist(
#'   DT,
#'   threshold = 100,
#'   id = 'ID',
#'   coords = c('X', 'Y'),
#'   timegroup = 'timegroup',
#'   returnDist = TRUE,
#'   fillNA = FALSE
#' )
#'
#' # Generate dyad id
#' dyad_id(edges, id1 = 'ID1', id2 = 'ID2')
#'
#' # Generate fusion id
#' fusion_id(edges, threshold = 100)
#'
#' # Directional correlation delay
#' delay <- edge_delay(
#'   edges = edges,
#'   DT = DT,
#'   window = 3,
#'   id = 'ID'
#' )
#'
#' # Leadership from directional correlation delay
#' leadership <- leader_edge_delay(
#'   delay
#' )
#'
