#' Leadership along group direction
#'
#' Given the mean direction of a group of animals, \code{leader_direction_group}
#' shifts the coordinate system to a new origin at the group centroid and
#' rotates the coordinate system by the mean direction to return each
#' individual's position along the mean direction, representing leadership in
#' terms of the front-back position in each group's mean direction.
#'
#' The function accepts a \code{data.table} with relocation data appended with a
#' \code{group_direction} column from \code{direction_group} and group centroid
#' columns from \code{centroid_group}. Relocation data should be in two columns
#' representing the X and Y coordinates.
#'
#' The \code{DT} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' The \code{group_direction} and \code{group} arguments expect the names of
#' columns in \code{DT} which correspond to the mean group direction generated
#' by \code{direction_group} and group column generated by \code{group_pts}. The
#' mean group direction column is expected in units of radians. The
#' \code{coords} arguments expects the names of columns in \code{DT} which
#' correspond to the X and Y coordinate columns. The \code{return_rank} argument
#' controls if the rank of each individual's distance to the group centroid is
#' also returned. The \code{ties.method} argument is passed to
#' \code{data.table::frank}, see details at
#' \code{\link[data.table:frank]{?data.table::frank}}.
#'
#' @return \code{leader_direction_group} returns the input \code{DT} appended
#'   with a \code{position_group_direction} column indicating the position along
#'   the group direction in the units of the projection and, optionally, a
#'   \code{rank_position_group_direction} column indicating the
#'   within group rank position along the group dirtection \code{return_rank =
#'   TRUE}).
#'
#'   A message is returned when \code{position_group_direction} or
#'   \code{rank_position_group_direction} columns already exist in the input
#'   \code{DT}, because they will be overwritten.
#'
#' @inheritParams direction_group
#' @inheritParams distance_to_centroid
#' @param group_direction group_direction column name generated using
#'   \code{direction_group}, default is 'group_direction'
#'
#' @export
leader_direction_group <- function(
    DT = NULL,
    group_direction = 'group_direction',
    coords = NULL,
    group = 'group',
    return_rank = FALSE,
    ties.method = 'average') {

  if (is.null(DT)) {
    stop('input DT required')
  }

  if (length(coords) != 2) {
    stop('coords requires a vector of column names for coordinates X and Y')
  }

  if (is.null(group)) {
    stop('group column name required')
  }

  xcol <- data.table::first(coords)
  ycol <- data.table::last(coords)

  centroid_xcol <- paste0('centroid_', gsub(' ', '', xcol))
  centroid_ycol <- paste0('centroid_', gsub(' ', '', ycol))

  check_cols <- c(coords, group, group_direction, centroid_xcol, centroid_ycol)

  if (any(!(check_cols %in% colnames(DT)))) {
    stop(paste0(
      as.character(paste(setdiff(
        check_cols,
        colnames(DT)
      ), collapse = ', ')),
      ' field(s) provided are not present in input DT'
    ))
  }

  if (any(!(DT[, vapply(.SD, is.numeric, TRUE), .SDcols = coords]))) {
    stop('coords must be numeric')
  }

  if (any(!(DT[, vapply(.SD, is.numeric, TRUE),
               .SDcols = c(centroid_xcol, centroid_ycol)]))) {
    stop('centroid coords must be numeric')
  }

  if (is.null(return_rank)) {
    stop('return_rank required')
  }

  if ('position_group_direction' %in% colnames(DT)) {
    message('position_group_direction column will be overwritten by this function')
    data.table::set(DT, j = 'position_group_direction', value = NULL)
  }

  DT[, position_group_direction :=
       cos(.SD[[group_direction]]) * (.SD[[xcol]] - .SD[[xcol_group]]) +
       sin(.SD[[group_direction]]) * (.SD[[ycol]] - .SD[[ycol_group]]),
     by = .I]

  if (return_rank) {
    if ('rank_position_group_direction' %in% colnames(DT)) {
      message('rank_position_group_direction column will be overwritten by this function')
      data.table::set(DT, j = 'rank_position_group_direction', value = NULL)
    }

    if (is.null(group)) {
      stop('group column name required')
    }

    if (!group %in% colnames(DT)) {
      stop('group column not present in input DT, did you run group_pts?')
    }

    DT[, rank_position_group_direction :=
         data.table::frank(-position_group_direction, ties.method = ties.method),
       by = c(group)]
  }

  return(DT[])
}
