#' Leadership along group direction
#'
#' Given the mean direction of a group of animals, \code{leader_direction_group}
#' shifts the coordinate system to a new origin at the group centroid and
#' rotates the coordinate system by the mean direction to return each
#' individual's position along the mean direction, representing
#' leadership in terms of the front-back position in group's mean direction.
#'
#' The function accepts a \code{data.table} with relocation data appended with
#' a \code{group_direction} column from \code{direction_group} and group
#' centroid columns from \code{centroid_group}. Relocation data should be in two columns representing the X and
#' Y coordinates.
#'
#' The \code{DT} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' The \code{group_direction} and \code{group} arguments expect the names of
#' columns in \code{DT} which correspond to the mean group direction generated
#' by \code{direction_group} and group column generated by \code{group_pts}. The
#' mean group direction column is expected in units of radians. The
#' \code{coords} arguments expects the names of columns in \code{DT} which
#' correspond to the X and Y coordinate columns. The \code{return_rank} argument
#' controls if the rank of each individual's distance to the group centroid is
#' also returned. The \code{ties.method} argument is passed to
#' \code{data.table::frank}, see details at
#' \code{\link[data.table:frank]{?data.table::frank}}.
#'
#' @return \code{leader_direction_group} returns the input \code{DT} appended
#'   with a \code{position_group_direction} column indicating the position along the
#'   group direction in the units of the projection and, optionally, a \code{rank_position_group_direction} column indicating the
#'   within group rank position along the group dirtection \code{return_rank =
#'   TRUE}).
#'
#'   A message is returned when \code{position_group_direction} or
#'   \code{rank_position_group_direction} columns already exist
#'   in the input \code{DT}, because they will be overwritten.
#'
#' @inheritParams direction_group
#' @inheritParams distance_tO_centroid
#' @param group_direction group_direction column name generated using \code{direction_group},
#' default is 'group_direction'
leader_direction_group <- function(
    DT,
    group_direction = 'group_direction',
    coords = NULL,
    group = 'group',
    return_rank = FALSE,
    ties.method = 'average') {

  xcol <- first(coords)
  ycol <- last(coords)
  xcol_group <- paste0('group_mean_', xcol)
  ycol_group <- paste0('group_mean_', ycol)

  stopifnot(group_bearing %in% colnames(DT))
  stopifnot(group %in% colnames(DT))
  stopifnot(xcol %in% colnames(DT))
  stopifnot(ycol %in% colnames(DT))
  stopifnot(xcol_group %in% colnames(DT))
  stopifnot(ycol_group %in% colnames(DT))

  DT[, dist_along_group_bearing :=
       cos(.SD[[group_bearing]]) * (.SD[[xcol]] - .SD[[xcol_group]]) +
       sin(.SD[[group_bearing]]) * (.SD[[ycol]] - .SD[[ycol_group]]),
     by = .I]

  if (return_rank) {
    DT[, N_by_group := .N, by = c(group)]
    DT[, rank_dist_along_group_bearing :=
         data.table::frank(-dist_along_group_bearing, ties.method = ties.method),
       by = c(group)]
  }

  return(DT)
}
