#' Leadership in directional correlation delay
#'
#' Given the directional correlation delay, \code{leader_edge_delay}
#' calculates the mean directional correlation delay for individuals in a
#' group to identify leadership patterns.
#'
#' The function accepts an edge list from \code{edge_delay} with columns
#' "dir_corr_delay" indicating the directional correlation delay between
#' individuals and "diff_direction" indicating the unsigned difference in
#' movement directions at the temporal delay.
#'
#' The \code{edge} must be a \code{data.table}. If your data is a
#' \code{data.frame}, you can convert it by reference using
#' \code{\link[data.table:setDT]{data.table::setDT}} or by reassigning using
#' \code{\link[data.table:data.table]{data.table::data.table}}.
#'
#' If \code{return_rank} is TRUE, the \code{group} argument is required to
#' specify the group column generated by \code{group_pts}. The
#' \code{ties.method} argument is passed to \code{data.table::frank}, see
#' details at \code{\link[data.table:frank]{?data.table::frank}}.
#'
#' @return \code{leader_edge_delay} returns the input \code{edges} appended with
#'   a \code{mean_delay} column indicating the mean directional correlation
#'   delay and, optionally when \code{return_rank = TRUE}, a
#'   \code{rank_mean_delay} column indicating the ranked mean directional
#'   correlation delay.
